name: Python testing

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  run_tests_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Bash script file
        run: |
          chmod +x ./.github/script/pytest.sh
          ./.github/script/pytest.sh
        shell: bash

      - name: Fetch ML assets
        run: |
          python3 ./ml_fetch.py
        shell: bash

  run_tests_on_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run PowerShell script file
        run: |
          .\.github/script/pytest.ps1
        shell: pwsh

      - name: Fetch ML assets
        run: |
          python ./ml_fetch.py
        shell: pwsh
